### ISSUE TITLE
Track page

### ISSUE THREAD

**Issue by ddorstijn** [CodeArtemis/TriggerRally#22]
At first: Happy new year!

So, what a really wante to say that a page where you can upload your awesome tracks wold be awesome. On the moment everybody has his own code(After the www.triggerrally.com/user/...).So it's really hard to play another one's track. it would be nice if there was just a seperated place where you can upload your track or browse trough the Userslist.

Drvanon :+1:

**Comment by ddorstijn** [comment]
And another think:

I like the game hoe it is. Don't say it isn't a very realistic game! The realistic collision was just the thing why i liked this game. :scream:

**Comment by jareiko** [comment]
Happy new year to you too! And thanks for the suggestions.

Don't worry, the center-of-gravity change I mentioned in #20 won't be huge, it will just make it slightly harder to roll the car when cornering.

I've already implemented a list of recent tracks, but I want to add a "public" checkbox to tracks before I publish it so that people can choose whether they want their track to appear on the list.

**Comment by copiousopioids** [comment]
Along the same lines as this, a way to delete unwanted tracks would be great. And an undo button :laughing:

**Comment by jareiko** [comment]
Deleting tracks shouldn't be too far off! Adding undo/redo is more difficult and not in my current plans, although it would be cool.

**Comment by jareiko** [comment]
This has now been implemented. You can "publish" your track and it will appear on the home page.

**Comment by jareiko** [comment]
Closing this issue with more updates:
- You can now view all recent tracks (published or not) [here](http://triggerrally.com/recenttracks)
- There's now a button in the editor to delete the track
