### ISSUE TITLE
Restart Enhancement

### ISSUE THREAD

**Issue by copiousopioids** [CodeArtemis/TriggerRally#30]
It would be really helpful to have a button like "r" restart the car as if if had been upside down for too long (like in the original TR). If you instituted that, it would also help to have the car NOT restart when upside down if the car is not touching anything (ie, flying through the air) to allow for epic flips and such :+1:

**Comment by jareiko** [comment]
Just to clarify, the terms I've been using are:
- Recover - flip the car the right way up when it's stuck upside down
- Restart - start the race again from the beginning (not yet implemented)

I've already added a "touching ground" requirement for recovery in v3, so epic flips should now be possible.

It would be possible to add a hotkey to recover immediately, but I think that having to use recovery should come with a significant time penalty, and the time waiting for recovery to activate is part of that penalty. Otherwise you can do things like drive really fast into a corner, and activate Recover to immediately lose all your speed. What do you think?

However, I am planning to add a Restart hot key, so that you don't have to reload the page each time.

**Comment by copiousopioids** [comment]
Coolness. Instead of having a long delay for recovery you could just add five seconds to the time and have the time turn red and then fade away to signify added time. Or just have the time not count at all if they use recover during a run.

**Comment by jareiko** [comment]
Good idea! I will probably do something like that.

**Comment by jareiko** [comment]
Restart with "R" is now live in v3. Recovery key (V?) with a time penalty is more tricky since it requires decoupling your race time from the simulation clock.

**Comment by copiousopioids** [comment]
I tried an "epic flip" and it still restarted me even though I wasn't touching anything. Something wrong here?

**Comment by jareiko** [comment]
Sorry, yes, the "epic flip" code is broken. I should be able to push a fix on Monday. (I'm game jamming this weekend.)

**Comment by jareiko** [comment]
Epic flip fix pushed.
