### ISSUE TITLE
Wrong shading on checkpoint gates with AMD Catalyst drivers on Linux

### ISSUE THREAD

**Issue by krasnoglaz** [CodeArtemis/TriggerRally#36]
Another irregularity with AMD drivers on linux. With my previous nvidia 8500 GT it looked smooth(although slow), now it has flat shading.

Just info for the author. I probably should find out which extension/call is failing in AMD drivers and file a bug in their unofficial wiki...

Catalyst 13.1, Ubuntu 12.04 Radeon 7950

![triggerrally-amd](https://f.cloud.github.com/assets/3269585/78864/1a97a8ce-6196-11e2-9de7-7dd166eda4fb.jpg)

**Comment by jareiko** [comment]
Don't worry! This is not a driver bug, it's a change in the model. I upgraded three.js from v49 to v54, and had to rebuild the models due to format changes. Because my skills in Blender are a bit lacking, I had to change the smoothing to fix some UV mapping problems, and I couldn't match the old look exactly.
