### ISSUE TITLE
Pixely Grossness

### ISSUE THREAD

**Issue by copiousopioids** [CodeArtemis/TriggerRally#45]
Love the improvements! One thing about the track editing. With ideal settings for flatness and with small embankments on the track, the track has to be lined up with (I'm guessing) a grid for terrain. When it's not, it makes for a bumpy track, but when it is, it's velvety smooth. Take a look: both checkpoints have exactly the same properties. Any way you could fix this (Maybe rotating grid depending on the angle change from the previous checkpoint)?
![obvi](https://f.cloud.github.com/assets/2965376/132792/de1c8592-7093-11e2-8911-975859203d95.png)

**Comment by jareiko** [comment]
Yep, that's the resolution of the base heightmap. It contains the default mountain terrain, and it's what you are modifying with the track curves. A "detail" heightmap is added to create smaller-scale bumps, but it doesn't provide fine control over the shape.

It's a system that allows fast rendering (1 draw call for the whole landscape) using vertex texturing, but unfortunately one side effect is what you describe here: you don't get fine control of the shape of the terrain.

Eventually, it would be nice to replace the 1-big-plus-1-small heightmap system with streamed higher-detail maps, which would allow creating landscapes of any shape. It won't be easy though.

By the way, the terrain pixels aren't square: they're 7.5m by 10.8m. So you can get a bit more detail in one direction than another. This is because the mountain satellite data originally came in this ratio, and resampling it would reduce the quality so I just left it like that.
