### ISSUE TITLE
Enhancement: Export Heightmap

### ISSUE THREAD

**Issue by copiousopioids** [CodeArtemis/TriggerRally#46]
Would it be possible to have an "Export Heightmap" button that would combine the detail and rough heightmaps and save the file as a grayscale heightmap? That way you could use it with the original TR and maybe later import homemeade heightmaps.

**Comment by ddorstijn** [comment]
Awesome!

**Comment by jareiko** [comment]
It's possible, but the file size would be enormous*. In order to export you'd have to downsample, but reducing the horizontal size and the vertical precision from 32 bit float to 8 bit grayscale would reduce the quality quite a lot. Might be something to consider once GIMP supports float images, or at least 16 bit per channel (supposed to be coming in version 3.0) because then you can cut out interesting regions and do manual downsampling to get the data into the original TR, which only supports 8 bit heightmaps.
- Quick calculation, the full heightmap size would be: 15360 by 22118 pixels, 32 bit float = 1.296 GB file size.

**Comment by copiousopioids** [comment]
Whoa, methinks a 1.3 GB file may be a little much to download. :D
