### ISSUE TITLE
Suspension / types simulation

### ISSUE THREAD

**Issue by Ivshti** [CodeArtemis/TriggerRally#48]
I am not actually sure, but the game definitely feels like there is no simulation of suspension at all. This definitely causes a lot of oddities in the control, such as easy car flipping. 

Also, I realize simulating an accurate tire model (flexible / etc) is difficult - but simple things, such as using a doughnut-shaped tire in the physics simulation (while still drawing a regular tire shape, of course) is a simple solution which comes a lot closer to an accurate flexible tire model.

**Comment by jareiko** [comment]
There is suspension simulation, but no tire simulation. However the travel is fairly short.

To look at one of the wheels more closely, you can press C (change camera) three times.

The model could probably use a bit more tuning, but of course it's difficult to get it right because the terrain in Trigger Rally is typically much bumpier than terrain you would really try to drive a car across.

Adding a tire simulation might help though, especially by providing more damping. Thanks for the suggestion!

**Comment by Ivshti** [comment]
Yes - that is a challenge in rally games - it's very hard to simulate real terrain properties (rally terrains are not perfectly solid), so other parts of the simulation must be compromised (e.g. softer suspension / tires) in order to achieve an overall more realistic result.

**Comment by jareiko** [comment]
I've made some improvements to the suspension simulation and increased the damping. What do you think?

**Comment by Ivshti** [comment]
Definitely changes the driving dramatically - for the better :)

**Comment by jareiko** [comment]
Great! Thanks for testing. I'll close this issue now.
