### ISSUE TITLE
Selection enhancements

### ISSUE THREAD

**Issue by copiousopioids** [CodeArtemis/TriggerRally#50]
I think that a way to select many objects at once would be handy (Not unlike a Desktop on an OS). Also, I wanted to use a trick by selecting multiple spots on the ground and placing arches there to make a tunnel, but it's harder since every time it places them at a different angle. An checkbox that appears when selecting multiple spots would be awesome (Makes missile silos AND tunnels possible) but just making multiple items spawn in the same orientation would suffice.
![Untitled](https://f.cloud.github.com/assets/2965376/190660/fe638f6a-7f04-11e2-95dc-ba09b134097f.png)

**Comment by jareiko** [comment]
Good idea! I thought that random orientations would be useful for scattering objects around, but more often when placing multiple objects you want them to be aligned. I'm making some big code changes at the moment but I will make this change when that's done, hopefully in a week or two.

**Comment by jareiko** [comment]
I made a change to the editor so that it will now align sequences of objects. Makes it easier to create (eg) fences along a straight line or even along a curve.

I didn't want to make the interface more complicated by including a "random angle" checkbox, and I'm not sure that missile silos are all that useful, really. ;)
