### ISSUE TITLE
where is the config file ?

### ISSUE THREAD

**Issue by yifei12100539** [CodeArtemis/TriggerRally#6]

**Comment by jareiko** [comment]
config.js is not checked in because it contains API secrets. It's not an
ideal situation but I can't think of any better way to do it.

I've pasted its current contents below, with secrets replaced with 'xxx'.
I'm not sure if MONGODB_DATABASE is actually used, now that I'm using
mongoose.

// Copyright (c) 2012 jareiko. All rights reserved.

// Configuration for databases, etc.

exports.FACEBOOK_APP_ID = 'xxx';
exports.FACEBOOK_APP_SECRET = 'xxx';
exports.TWITTER_APP_KEY = 'xxx'
exports.TWITTER_APP_SECRET = 'xxx';
exports.SESSION_SECRET = 'xxx';

exports.MONGODB_HOST = 'xxx';
exports.MONGODB_PORT = 27017;
exports.MONGODB_DATABASE = 'trigger';

MONGOOSE_HOST = 'xxx';
MONGOOSE_DB = 'trigger-prod';

exports.MONGOOSE_URL = 'mongodb://' + MONGOOSE_HOST + '/' + MONGOOSE_DB;

**Comment by yifei12100539** [comment]
2012/9/27 Jasmine Kent notifications@github.com

**Comment by cnip** [comment]
local stragy may be a choice ,, waiting for the detail !!
