### ISSUE TITLE
Trigger Rally is down :o

### ISSUE THREAD

**Issue by jareiko** [CodeArtemis/TriggerRally#76]
After more than 6 months of broken login, I tried to test #73 today but due to a combination of old, stale out of date OS and packages, the whole system broke down and now I can't even get the game running.

Maintaining the Trigger Rally server and database has been difficult, and although I could try to rebuild the server with fresh versions of everything, I would prefer to try a new approach: host everything on github pages. This would have the benefit of making it super easy for people to fork and modify the game, but I don't know how to support the track editor in that environment. Suggestions welcome!

I will try to work on this new approach but can't make any promises about timeline.

**Comment by parkerlreed** [comment]
D: Hope you get everything worked out

**Comment by jareiko** [comment]
**Update:** I have the basics running here:
http://codeartemis.github.io/TriggerRally/server/public/

Next I need to fix the base path for client-side routing, and then start replacing the server API calls with local data.

**Comment by jhonphilipps** [comment]
Mais c'est la meilleur nouvelle que je puisse entendre !! ce serait un réel plaisir si je pouvais aider au développement, c'est dommage que depuis quelques temps le jeux sois cassé. ce serait bien aussi d'avoir un contrôle de modérateur éventuellement pour les chronos à cause des cheaters :) je suis impatient de refaire un challenge à la sauce triggerrally ;) ce serait bien aussi pour la prochaine release que les trois type de véhicules deviennent accessibles genre étapes après étapes en réussissant des challenges? Garder le système de donation c'est évident mais aussi pourquoi ne pas ouvrir une boutique de contenu additionnel (skin, effect, decor object)? j'ai encore plein d'idées si besoin et je me défends sur blender :) ... toujours un plaisir de te lire , salutations et bon courage J.
But it's the best news I could hear !! it would be a pleasure if I could help in development, it's a shame that for some time the games be broken. it would be nice also to have a moderator to control the times possibly because of cheaters :) I can not wait to make another challenge to triggerrally sauce ) it would be good also for the next release that the three types of vehicles become available such steps after steps by completing challenges? Keep the donation system that is obvious but why not open a store additional content (skin , effect , decor object) ? I still have lots of ideas and if necessary I defend myself on blender :) ... always a pleasure to read you , greetings and good luck J.

**Comment by SuperScratch** [comment]
:( I loved trigger raly

**Comment by jareiko** [comment]
I'm very sorry, but it's heartening that someone did notice that it's down!

**Comment by SuperScratch** [comment]
Its okay ican wait

**Comment by wangyapeng** [comment]
its crazy

**Comment by imjasonmiller** [comment]
I just watched your talk and was excited to try it out again after having played it before quite some time ago. I wish I could be of help, but unfortunately I just started out with Three.js.

**Comment by QwertzyK** [comment]
Is it possible for you to add a mode into the game where there isnt a time limit in the new version u made?

**Comment by R3c0nf1gur3d** [comment]
My friends and I used to play this all of the time at school. Loads of fun. When you get it up and running again, can you get the logins for gmail working again? Can't wait to play it again. 3d rendering is incredible.

**Comment by Kyl3lrod** [comment]
Oh man its been 4 months! I miss trigger rally! I laugh so hard at that game because of the funny glitches! Hows it been going?

**Comment by Kyl3lrod** [comment]
can we see the update?

**Comment by jareiko** [comment]
The work in progress as of January is here:

http://codeartemis.github.io/TriggerRally/

But you can see that only the sky is loading, and if you open the JavaScript console there are some errors, and I haven't had time to fix them.

If anyone is able to take a look I'd really appreciate it. Otherwise, still no ETA for this, sorry.

**Comment by jhonphilipps** [comment]
sorry i can't help :( i prey for you to fix it ;)

Le 04/06/2016 à 01:41, Jasmine Kent a écrit :

The work in progress as of January is here:

http://codeartemis.github.io/TriggerRally/

But you can see that only the sky is loading, and if you open the JavaScript console there are some errors, and I haven't had time to fix them.

If anyone is able to take a look I'd really appreciate it. Otherwise, still no ETA for this, sorry.

**Comment by vaektor** [comment]
What's the target OS? Ubuntu?

**Comment by wuqianhua** [comment]
perfect

**Comment by RastkoM** [comment]
swdasd

**Comment by jude802** [comment]
This was my favorite game last year, I had so many coins... I tried to get #1 on every popular course that was uploaded, and i came damn close to getting them at one point. Rip game ;-;

**Comment by HarryTench** [comment]
Its bad that we haven't heard a update from the creator in over a year...

**Comment by Tomoli75** [comment]
still down

**Comment by parkerlreed** [comment]
@Tomoli75 I think it's safe to assume this isn't coming back. WebGL has progressed over the years and the codebase might not be in any shape worth fixing. It was a fun game but always remember, it's based on another FOSS piece of software you can still use. http://trigger-rally.sourceforge.net/

**Comment by DVLP** [comment]
![image](https://user-images.githubusercontent.com/5261364/53303953-3b0d6a80-3868-11e9-9abe-d7c3131752f1.png)

What I wanted was just to reverse engineer part of the terrain editor for my own game and engine https://bad.city but ended up resurrecting TriggerRally because it's one of the best Three.js and WebGL examples available. Not just an experiment but a real product.

I never used coffee script before and just spent all night and day to get this to work but slowly managed to breakpoint and console.log my way through. Found missing assets online(car JSON model, demo track from some old website dump https://github.com/sqliu/TriggerRally/tree/master/ ), found compatible packages version, I updated some and updated the code. 

Ignore this error, it's automatically loading a fallback: Error: Cannot find module '../build/Release/bson'

It appears to work again!

branch "resurrect" in my fork https://github.com/BadCityGame/TriggerRally/tree/resurrect
PR https://github.com/CodeArtemis/TriggerRally/pull/78

**Comment by parkerlreed** [comment]
:D sweet. Is this hosted anywhere at the moment? (About to try the local server)

**Comment by jareiko** [comment]
Wow, fantastic! Thank you @DVLP! @parkerlreed: did you get it to work? I don't have time to test it myself right now.

I think it would be amazing if this could run off GitHub Pages, but I'm not sure how to handle the need for a backend database.

**Comment by parkerlreed** [comment]
Naah, I got some errors spat back.

```
[parker@stealth server]$ npm start

> trigger-server@0.0.1 start /home/parker/build/TriggerRally/server
> coffee app.coffee

{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/parker/build/TriggerRally/server/node_modules/mongoose/node_modules/bson/ext/index.js:15:10)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (/home/parker/build/TriggerRally/server/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/parker/build/TriggerRally/server/node_modules/mongoose/node_modules/bson/lib/bson/index.js:3:24)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (/home/parker/build/TriggerRally/server/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/parker/build/TriggerRally/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/index.js:2:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (/home/parker/build/TriggerRally/server/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/parker/build/TriggerRally/server/node_modules/mongoose/lib/utils.js:5:16)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (/home/parker/build/TriggerRally/server/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/parker/build/TriggerRally/server/node_modules/mongoose/lib/schema.js:7:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (/home/parker/build/TriggerRally/server/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/parker/build/TriggerRally/server/node_modules/mongoose/lib/index.js:7:14)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (/home/parker/build/TriggerRally/server/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/parker/build/TriggerRally/server/node_modules/mongoose/index.js:7:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (/home/parker/build/TriggerRally/server/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/parker/build/TriggerRally/server/app.coffee:14:21)
    at Object.<anonymous> (/home/parker/build/TriggerRally/server/app.coffee:1:1)
    at Module._compile (module.js:653:30)
    at Object.exports.run (/home/parker/build/TriggerRally/server/node_modules/coffee-script/lib/coffee-script/coffee-script.js:173:23)
    at compileScript (/home/parker/build/TriggerRally/server/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
    at compilePath (/home/parker/build/TriggerRally/server/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
    at Object.exports.run (/home/parker/build/TriggerRally/server/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
    at Object.<anonymous> (/home/parker/build/TriggerRally/server/node_modules/coffee-script/bin/coffee:15:45)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
 code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
[2019-02-26T16:26:08.597Z] Base directory: /home/parker/build/TriggerRally/server
[2019-02-26T16:26:08.628Z] Server listening on port 80 in development mode
Option log level is not valid. Please refer to the README.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1343:19)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at Object.<anonymous> (/home/parker/build/TriggerRally/server/app.coffee:528:8)
    at Object.<anonymous> (/home/parker/build/TriggerRally/server/app.coffee:1:1)
    at Module._compile (module.js:653:30)
    at Object.exports.run (/home/parker/build/TriggerRally/server/node_modules/coffee-script/lib/coffee-script/coffee-script.js:173:23)
    at compileScript (/home/parker/build/TriggerRally/server/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
    at compilePath (/home/parker/build/TriggerRally/server/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
    at Object.exports.run (/home/parker/build/TriggerRally/server/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
    at Object.<anonymous> (/home/parker/build/TriggerRally/server/node_modules/coffee-script/bin/coffee:15:45)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! trigger-server@0.0.1 start: `coffee app.coffee`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the trigger-server@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/parker/.npm/_logs/2019-02-26T16_26_08_637Z-debug.log
```

**Comment by parkerlreed** [comment]
Ok that bson not found wasn't the bailing error. The error was it was trying to start on port 80 as normal user... I changed it to 8080 but now it bails at not finding the mongodb server running. @DVLP Do I need to start the database separately?

```
Error: failed to connect to [localhost:27017]
    at exports.ConnectionPool.<anonymous> (/home/parker/build/TriggerRally/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:556:25)
    at emitThree (events.js:136:13)
    at exports.ConnectionPool.emit (events.js:217:7)
    at exports.Connection.<anonymous> (/home/parker/build/TriggerRally/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at emitTwo (events.js:126:13)
    at exports.Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/home/parker/build/TriggerRally/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! trigger-server@0.0.1 start: `coffee app.coffee`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the trigger-server@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/parker/.npm/_logs/2019-02-26T16_27_52_189Z-debug.log
```

**Comment by parkerlreed** [comment]
I DID NEED TO START MONGODB :D
![image](https://user-images.githubusercontent.com/841440/53429083-ed087c00-39b9-11e9-8a15-3003cd87e700.png)

**Comment by parkerlreed** [comment]
Ok so next up would be patching out the car check :wink:

![image](https://user-images.githubusercontent.com/841440/53429267-48d30500-39ba-11e9-8196-8f2965653af4.png)

**Comment by parkerlreed** [comment]
And yeah only has that single track. Still amazing. Thanks @DVLP

**Comment by parkerlreed** [comment]
Video https://www.youtube.com/watch?v=rDJ9OhJDkZk

**Comment by jareiko** [comment]
Yayyy! Okay I'm going to merge this from sheer enthusiasm.

**Comment by parkerlreed** [comment]
@jareiko Do you still have all the old user created levels? Would be kinda cool to get those going.

**Comment by DVLP** [comment]
@jareiko I'm glad you're happy and don't mind merging these assets in. I guess in the past it was important to keep them separately because that was part of the potential business. If you still want to keep them separately in the future I have some other terrain map which I can add under MIT license, and the car shouldn't be difficult to make because it's just one solid mesh without moving parts(except of the wheel).
@parkerlreed yay!

**Comment by jareiko** [comment]
Yes, that was the idea. But I don't intend to pursue the game as a business anymore, and am happy if it can be a useful learning resource for others.

I don't remember what the licensing situation is for the assets. I guess the cars and terrain might be proprietary, so it would be good to switch them out for truly free ones at some point.

Thank you for doing this - it makes me very happy to see it running again!

**Comment by DVLP** [comment]
It is fun to restore a project which is using now-outdated versions of packages and coffee script. It feels like archeology work but at the same time it's a nicely written and polished code with many interesting and relevant elements so with some work can be updated to the latest features of desktop Trigger Rally and beyond.

The first step I see here is updating THREE to the latest version. Here's a commit with broken render but at least things are working and not throwing errors. https://github.com/BadCityGame/TriggerRally/commit/d3292b784f0050d95554a0237f3a7894871ef5da

Things are rendering in black because I commented out the materials for now, updating them might be more difficult than updating the API because Chrome's debugger is not too specific for WebGL errors i.e. "syntax error" and entire shader printed out

No miracles yet but this is THREE 101 version!
![image](https://user-images.githubusercontent.com/5261364/53457130-0d235400-3a29-11e9-8858-b00743b45f0c.png)

**Comment by DVLP** [comment]
Getting there, the terrain shader works with some small lighting issue, the car is loaded but invisible for some reason
![image](https://user-images.githubusercontent.com/5261364/53532626-7a012180-3aef-11e9-87ab-4730739329f7.png)

Edit: now it's visible, for some bizarre reason setting transparency to something else than 0.0 in it's JSON file makes it appear 
![image](https://user-images.githubusercontent.com/5261364/53533550-39a3a280-3af3-11e9-9bc8-46b9fbcf78a4.png)

**Comment by DVLP** [comment]
Shaders(terrain with shadows, dust, skybox) updated for THREE 101. Dust points geometry updated to BufferGeometry with flat array attributes.
https://github.com/BadCityGame/TriggerRally/commit/f3825cb6600d38ae5f27b1ea12b4be6460ac9210

Still on todo's list: 
-Transpile to ES6
-Fix dust from under the wheels is only visible when reversing
-Fix scenery objects(gates, road signs, trees) not loading in Chrome

![image](https://user-images.githubusercontent.com/5261364/53770771-400d9200-3ed8-11e9-9bbb-6e01127feace.png)

**Comment by parkerlreed** [comment]
I got so excited to play a level without trees, until I realized they are there just not rendered lol

![image](https://user-images.githubusercontent.com/841440/53821410-be4f5000-3f3b-11e9-9af3-35487ad49a46.png)

Thanks!

**Comment by parkerlreed** [comment]
Also FWIW it doesn't render those objects in Firefox either. Is it rendering them anywhere?

**Comment by DVLP** [comment]
@jareiko If you want I can make a PR for this now. Now only the dust effect is missing. Dust particles are visible only during reversing so this must be a one liner fix which may take a few hours to debug.
@parkerlreed I didn't have time to work on this until the last night and now the objects are all loading in the branch
![image](https://user-images.githubusercontent.com/5261364/54445308-659e6500-473c-11e9-887e-9ea8f8688802.png)

**Comment by DVLP** [comment]
As CoffeeScript didn't stand the trial of time and JavaScript caught up with all the cool features I converted the whole thing(client and server) to JavaScript. It should be easier for other enthusiasts to pick up and modify the project now https://github.com/CodeArtemis/TriggerRally/pull/79
This shows the power of https://github.com/decaffeinate/decaffeinate project. With just a few hours of additional manual work it's all converted and working.

I left the suggestions generated by decaffeinate in the code, they will be useful during conversion to JS modules

**Comment by DVLP** [comment]
Finally I managed to find some time to extract the terrain renderer. I barely managed to understand and remove _quiver_ which is some kind of streams/pubsub like RxJS with many to many relationships but without documentation it was really difficult to follow. For now I replaced it with good old **window** globals :) Event emitter and callbacks should be enough to make this work properly without going into streams world so beginners who want to learn from the code won't get lost.
https://codesandbox.io/s/jl630vozl9

I'm going to reimplement this into the game when I'll find some time to turn everything into ES6 modules

Broken textures are not a problem but I'm having problems with the layers having gaps between them:
![image](https://user-images.githubusercontent.com/5261364/56869220-91786000-69f5-11e9-8e0d-6bd74bd89311.png)

**Comment by jareiko** [comment]
Wow, this is so cool! At first glance, it looks like there is no morphing happening at the edges of the terrain. I think this was computed in the vertex shader. Maybe it's missing from this sandbox?

**Comment by DVLP** [comment]
Vertex shader is the problem and I can see that playing with numLayers and ringWidth params in renderTerrain.js is making the gaps more/less noticeable. Except of modifying the shader to adapt it the latest Three version I haven't invested much time into understanding how the tiles system works because GLSL is not my strongest side yet. The whole thing might also be caused by the plane lying on XZ axis instead of XY like originally in TR. It's worth mentioning that OrbitCamera is being used here and it's position is relative to it's target.

**Comment by DVLP** [comment]
![image](https://user-images.githubusercontent.com/5261364/56871571-d7462000-6a17-11e9-85bd-9cc44fc3d851.png)
just like suspected. I'm using default Three coordinates where Y is up and Z goes towards the camera. In the game Z is up and Y away from the camera. For now I hardcoded a fix 

before:
```
    // Work out how much morphing we need to do.
    vec3 manhattan = abs(worldPosition - cameraPosition);
```
after:
```
    vec3 cameraPosYUp = vec3(cameraPosition.x, -cameraPosition.z, cameraPosition.y);
    // Work out how much morphing we need to do.
    vec3 manhattan = abs(worldPosition - cameraPosYUp);
```
Probably this could be happening automatically by multiplying one of the values by one of the view matrices. I tried that but it doesn't seem to work

https://codesandbox.io/s/48mxrwz2j4

**Comment by Good51038** [comment]
Hi. Iam from Russia and I was playing in this game before it crashed a couple years ago. I would to know, could i play it now? Or it does not fixed yet? And if game is Ok, what I need to do, to play it? 
P.S.: Ty, for yours reply!

**Comment by RallyFan2020** [comment]
and there goes a game that I played years ago, and it marked me a lot, goodbye trigger rally I hope that one day the guys will revive this game or the developers will return this game to active because I'm upset today, nothing new about the trigger rally , this is already a sign that the game died  :(

**Comment by gre** [comment]
Internet moves fast

**Comment by gre** [comment]
Internet moved fast

**Comment by DVLP** [comment]
Not down anymore! https://github.com/CodeArtemis/TriggerRally/pull/85

**Comment by parkerlreed** [comment]
:O YESSSS. Thank you

**Comment by Tomoli75** [comment]
This is marvellous news!

**Comment by wrencherd** [comment]
🙌👍
________________________________

**Comment by jareiko** [comment]
Thank you @DVLP !! :heart:

https://codeartemis.github.io/TriggerRally/server/public/

**Comment by DVLP** [comment]
You're welcome 😄

**Comment by kylaxial** [comment]
I made an account just to reach out that only one of the features of Trigger Rally works, and I really want the full experience of Trigger Rally, like viewing other tracks, making your own tracks, and the other vehicles to work, so I am wanting to help in any way I can to reach that goal... but first, I'm very new to GitHub, so is there a guide somewhere so I would know what to do first? or will this comment just go unnoticed by everyone in the future? I know I won't be able to figure this out on my own. this issue is already closed, but I don't know where else to put this comment.

**Comment by jareiko** [comment]
Hi @kylaxial! The features you mention require a backend server and database to be running. DVLP modified the front end to work when served directly from GitHub, which allows the driving mode to work again.

So in order to restore the full functionality, we would need someone to:

a) set up a MongoDB instance
b) bring up the TriggerRally server (the code is included in this git repo)
c) update the server to the latest nodejs and libraries, since there are likely to be security issues with the ten-year-old code
d) connect the front end to the server, preferably in a way that allows the front end to continue to be hosted on GitHub Pages or other static hosting site

So it's possible, but quite a bit of work to get it all running and debugged.

**Comment by kylaxial** [comment]
Ok, I have installed MongoDB, and now I'm not sure what to do next... I'm very new to this, so expect a lot of questions like this in the future if you're still willing to help me then.
![what next](https://user-images.githubusercontent.com/101967694/160022502-edaf079f-8a3a-45fd-bd77-74ff3486d2d4.png)

Nevermind, I think I figured out how to get past that screen, and now I'm on this screen
![what now](https://user-images.githubusercontent.com/101967694/160024325-1d080ca5-a39d-416b-8e5b-61e2448db0de.png)

**Comment by jareiko** [comment]
Thank you for your efforts on this, @kylaxial! But unfortunately I won't be able to help you with it step by step.

**Comment by wrencherd** [comment]
I'm sorry to hear that TR is down.

I've always enjoyed it and will very much miss the distinctive and thrilling crunch of gravel. 😉

thanks to CA and the rest of the authors/maintainers for all of their work in keeping it alive to this point.

cheers all
________________________________

**Comment by kylaxial** [comment]
> Thank you for your efforts on this, @kylaxial! But unfortunately I won't be able to help you with it step by step.

if you can't help me with it step by step, can you at least take me to some kind of guide where I would know what to do next?

**Comment by EtherealSoul96** [comment]
Hello everyone, I have good news!
I've spent the last three weeks restoring most of the features that required an external database, adapting them for local use.
Instead of depending on a server you can now store tracks and runs locally (using IndexedDB).

Things restored:
- Track editor
- Storing the tracks you make and displaying them in the tracks list
- Saving your runs and displaying them in the runs list 
- Racing against a run's ghost

You can now also download and upload tracks and runs as files!
So even though it's not real-time, we can start creating and sharing tracks and competing for times.

I've also created a Discord server for that purpose and to discuss what other changes would be cool to add to the game.
Now I'll start studying for exams for about a month and a half so I won't be able to make big changes for a while, but I plan to continue making improvements to the game throughout the year.

Meanwhile it would be cool if we can start forming a community, even if we are only a few in the beginning :)

---

You can try the updated game here:
https://etherealsoul96.github.io/TriggerRally/

Discord server:
https://discord.gg/3HRzS9xyum

Some tracks I've made and example runs you can import into the game:
https://drive.google.com/drive/folders/1FBrE8lcwum5MppXxsg2EnNFVRpMP4MWR
(download them, click "upload" in the game, and select them all together)

@jareiko I've put these changes in a separate branch and opened a PR in case you want to merge them.  #102

**Comment by parkerlreed** [comment]
Awesome! Are the car assets unlockable? I miss the other two very much.
